/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as DistributorSplatRouteImport } from './routes/distributor.$'
import { Route as DashboardSplatRouteImport } from './routes/dashboard.$'
import { Route as CrmSplatRouteImport } from './routes/crm.$'
import { Route as AgentSplatRouteImport } from './routes/agent.$'
import { Route as AdminSplatRouteImport } from './routes/admin.$'

const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorSplatRoute = DistributorSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DistributorRoute,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRoute,
} as any)
const CrmSplatRoute = CrmSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CrmRoute,
} as any)
const AgentSplatRoute = AgentSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AgentRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/distributor': typeof DistributorRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/rent': typeof RentRoute
  '/admin/$': typeof AdminSplatRoute
  '/agent/$': typeof AgentSplatRoute
  '/crm/$': typeof CrmSplatRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/distributor/$': typeof DistributorSplatRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/distributor': typeof DistributorRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/rent': typeof RentRoute
  '/admin/$': typeof AdminSplatRoute
  '/agent/$': typeof AgentSplatRoute
  '/crm/$': typeof CrmSplatRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/distributor/$': typeof DistributorSplatRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/distributor': typeof DistributorRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/rent': typeof RentRoute
  '/admin/$': typeof AdminSplatRoute
  '/agent/$': typeof AgentSplatRoute
  '/crm/$': typeof CrmSplatRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/distributor/$': typeof DistributorSplatRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/agents'
    | '/blog'
    | '/builders'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/distributor'
    | '/login'
    | '/projects'
    | '/rent'
    | '/admin/$'
    | '/agent/$'
    | '/crm/$'
    | '/dashboard/$'
    | '/distributor/$'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/agents'
    | '/blog'
    | '/builders'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/distributor'
    | '/login'
    | '/projects'
    | '/rent'
    | '/admin/$'
    | '/agent/$'
    | '/crm/$'
    | '/dashboard/$'
    | '/distributor/$'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/agents'
    | '/blog'
    | '/builders'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/crm'
    | '/dashboard'
    | '/distributor'
    | '/login'
    | '/projects'
    | '/rent'
    | '/admin/$'
    | '/agent/$'
    | '/crm/$'
    | '/dashboard/$'
    | '/distributor/$'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  BlogRoute: typeof BlogRoute
  BuildersRoute: typeof BuildersRoute
  BuyRoute: typeof BuyRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DistributorRoute: typeof DistributorRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  RentRoute: typeof RentRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/$': {
      id: '/distributor/$'
      path: '/$'
      fullPath: '/distributor/$'
      preLoaderRoute: typeof DistributorSplatRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/crm/$': {
      id: '/crm/$'
      path: '/$'
      fullPath: '/crm/$'
      preLoaderRoute: typeof CrmSplatRouteImport
      parentRoute: typeof CrmRoute
    }
    '/agent/$': {
      id: '/agent/$'
      path: '/$'
      fullPath: '/agent/$'
      preLoaderRoute: typeof AgentSplatRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentSplatRoute: typeof AgentSplatRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentSplatRoute: AgentSplatRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface CrmRouteChildren {
  CrmSplatRoute: typeof CrmSplatRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmSplatRoute: CrmSplatRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface DashboardRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DistributorRouteChildren {
  DistributorSplatRoute: typeof DistributorSplatRoute
}

const DistributorRouteChildren: DistributorRouteChildren = {
  DistributorSplatRoute: DistributorSplatRoute,
}

const DistributorRouteWithChildren = DistributorRoute._addFileChildren(
  DistributorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  AgentsRoute: AgentsRoute,
  BlogRoute: BlogRoute,
  BuildersRoute: BuildersRoute,
  BuyRoute: BuyRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DistributorRoute: DistributorRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  RentRoute: RentRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
